version: '3'
tasks:
  run-local:
    cmds:
      - go run .
  apply:
    cmds:
      - cat kube.yaml | envsubst '$OPENAI_API_KEY' | kubectl apply --prune -l "app=kupilot" -f -
      - kubectl -n kupilot rollout restart deployment/kupilot
  connect:
    cmds:
      - kubectl -n kupilot exec -it $(kubectl get pods -n kupilot -l app=kupilot -o jsonpath='{.items[0].metadata.name}') -- kupilot
  record-gif:
    cmds:
      - vhs docs/debug-nginx-healthcheck.tape
  release:
    cmds:
      - goreleaser release --clean --draft --fail-fast
