Output docs/debug-nginx-healthcheck.gif
Set Width 800
Set Height 800
Set FontSize 10
Set LineHeight 1.4
Set Padding 5
Type@10ms "docker run --rm -it -e OPENAI_API_KEY=$OPENAI_API_KEY -e SEED=1 -e KUBECONFIG=/.kube/config -v ~/.kube:/.kube ghcr.io/r2k1/kupilot:latest kupilot"
Sleep 500ms
Enter
Sleep 1s
Type "What is wrong with nginx?"
Enter
Sleep 5s
Type "Just do it!"
Enter
Sleep 5s
Type "y"
Enter
Sleep 5s
Type "y"
Enter
Sleep 5s
Type "y"
Enter
Sleep 15s
Type "y"
Enter
Sleep 15s
